apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: my-simple-web-app
        image: ivaylokenov/simple-web-app:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 8080
