kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: google-ssd
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-ssd
  replication-type: none