version: "3"

services: 
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - "1433:1433"
        env_file: development.env
        volumes: 
            - sqldata:/var/opt/mssql 
        networks: 
            - my-network
    web_app:
        container_name: web_app
        build: 
            context: .
            dockerfile: ./Dockerfile
        ports: 
            - "5000:80"
        restart: on-failure
        networks: 
            - my-network
        depends_on: 
            - sqlserver

volumes:
    sqldata:
networks: 
    my-network: