apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-client
spec:
  selector:
    matchLabels:
      web-client: user-client
  template:
    metadata:
      labels:
        web-client: user-client
        system: client
    spec:
      containers:
      - name: user-client
        image: profjordanov/carrentalsystem-user-client:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"