apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      name: web
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: my-simple-web-app
        image: ivaylokenov/simple-web-app:2.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 8080
