apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ps-fast
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      usage: my-storage
