apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
  labels:
    usage: my-storage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ps-fast
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: my-disk