apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    name: web
spec:
  containers:
  - name: my-simple-web-app
    image: ivaylokenov/simple-web-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
